export const m =
{
    "contact": "Contact",
    "hygiene": "Hygiene",
    "clothes": "Textile",
    "industry": "Industry",
    "home": "Home",
    "about": "About",
    "reseller": "Reseller",
    "total_amount" :"Total Amount",
    "quantity_items" :"Quantity",
    "average" :"Average",
    "search" :"Search",

    "subscribe" :"subscribe",
    "follow": "Follow us",
    "shiping" :"Shiping",
    "faq" :"FAQ",
    "how_to_buy" :"How to purchase",
    "cobranding" :"COBRANDING",

    "send": "Send",
    "cancel": "Cancel",
    "modify": "Modify",
    "save": "Save",
    "update": "Update",
    "acept": "To Accept",
    "new": "New",
    "high": "High",
    "anular_p": "Cancel Order",
    "go_back": "Go back",
    "code" : "Verification Code",
    "validate_mail" : "Validate Email",
    "validate_mail_ok" : "Email Validated Correctly",
    "validate_mail_error" : "Invalid Confirmation Code",

    "suscription_success": "Successfully registered. You will soon receive all our news",
    "suscription_error": "There was an error registering the mail. Please try again later",
   
    "reseller_email_error":"Email already registered. If you don't remember your password you can request a reset",
    "reseller_id_error":"CUIT or DNI already registered. If you don't remember your password you can request a reset",
    "reseller_success":"The form was successfully submitted. We will get in touch soon",
    "reseller_error":"There was an error registering the mail. Please try again later",
   
    "max_lenght_error": "You have exceeded the maximum number of characters.",
    "email_error": "Please enter a valid email format.",
    "min_lenght_error": "Please enter at least 2 characters",
    "required_error": "Please complete all fields.",
    "choose_state":"Select a state",
    "choose_city":"Select a city",
    "limit_numeric":"4 digits",

    "my_perfil": "My Profile",
    "my_datos": "My Data",
    "datos_g": "General Information",
    "t_client": "Type of Clients",
    "A_client": "Client Management",
    "client": "Customers",
    "confirm_delet_cliente1": "Sure you want to Delete the Client",
    "confirm_delet_cliente2": "This action cannot be undone. Remember that you cannot Delete Clients who have Orders and / or Invoices made", 
    "send_email_clave": "Send mail to User with new Password?",
    "user_edit": "The Data Was Updated Correctly",
    "user_edit_error": "There was a General error while updating the data",

    "message_numeric":"Only numbers, no spaces, hyphens, or periods",
    "ok_message":"Ok",



    "most_wanted": "Most popular",

    "about_as": "About us",
    
    "categories": "Categories",
    "howbuy": "How to purchase",

    "presentations": "Buying options",
    "buy": "Add to Cart",
    "buy_now": "Login To Buy",
    "select_packaging": "Select",
    "related_items": "Related Items",
    "modal_title": "Product Added to Cart",
    "modal_btn_categories": "Back to category",
    "modal_btn_categories_home": "Go to category home",
    "modal_btn_categories_hygiene": "Go to category hygiene",
    "modal_btn_categories_clothes": "Go to category clothes",
    "btn_categories": "Go to Categories",
    "modal_btn_close": "Stay on this page",
    "modal_btn_cart": "Go to cart",
    "now": "NOW",

    "from": "from",


    "full_name":"Full Name or Company Name",
    "cuit":"CUIT or DNI",
    "state":"State",
    "city":"City",
    "street":"Address",
    "between_streets" : "Between Streets",
    "zip":"Zip code",
    "number":"Number",
    "floor":"Floor",
    "address_required": "Address is Required",
    "d_fact": "Financial data",
    "saldo_f": "Total Outstanding Balance",
    "estado": "State",
    "obsv": "Observation",


    "item":"Items",
    "amount":"Amount",
    "unitary": "Unitary",
    "go_checkout":"Confirm Purchase",
    "keep_buying":"Keep Shopping",
    "empty_cart":"Empty cart",
    "checkout": "Finalize New Orders",
    "checkout2": "Finish Order Modification #",
    "date_delivery": "Approximate delivery date",
    "obsv": "Observation",
 
 
    "id":"Personal Information",
    "shipping_address":"Shipping Address",
    "payment":"Payment",
    "summary":"Purchase Summary",
    "close":"Close",
    "first_name": "First Name",
    "last_name": "Last Name",
    "celphone": "Phone",
    "goto_shipp": "Go to shipping", 
    "bill_info" : "If you need an A, B or E invoice under the name of another person, you can request it in the user panel once the order has been completed.",
    "goto_payment" : "Go to payment",
    "autorize_shipping" : "Complete if you authorize another person to receive",
    "make_order" : "Place order",
    "subtotal": "Subtotal",
    "shipping": "Shipping",
    "total": "Total",
    "discount": "Discount",
    "free_shipping": "Free Shipping",
    

    "leave_message": "Leave us your message",
    "ForWhom": "Select destination",
    "name": "Name",
    "email": "Email",
    "phone": "Phone",
    "message": "Message",
    "customer_support": "Customer Support",
    "reseller_support": "Reseller Support",

    "order_complete":"ORDER COMPLETE",
    "thanks_order":"THANK YOU FOR YOUR PURCHASE",

    "password": "Password",
    "repeartpassword": "Repeart Password",
    "password_min": "Minimum Password of 8 Characters",
    "password_mismatch": "Password Mismatch",
    "password_ok": "Pasword Ok",
    "password_success": "The User's Password Was Modified Correctly",
    "password_error": "There was an Error Changing the password, please contact the administrator",
    "password_new": "Enter a New Password",
    "password_change": "Change Password",

    "welcome_l1": " Welcome to the Clients area of Swell.com.ar",
    "welcome_l2": " If you already have an account, ",
    "welcome_l22": " click here.",
    "welcome_l3": " If you want to start buying and / or selling our products, fill out the following form and then a representative of our team will contact you shortly. ",
    "welcome_l4": " Thank you! Swell's team ",

    "about_l1": " is a company that has a history of 19 years in the manufacture of hygiene and cleaning products, with constant investments in technology and development of new products. We have high quality standards at very competitive prices.",
    "about_l2": " We are a company committed to the environment, the personal and professional development of those who make it up, constantly training us.",
    "about_l3": " We add value throughout the chain by adapting to the needs of our customers, providing them with excellent service. Initially we emphasized our productions and marketing in various industries throughout the country, achieving the expansion of our business by introducing ourselves in the channels of distributors, wholesalers and finally with a presence in the final consumer as well as in the export market.",
    "about_l4": " Our Mission is to bring high quality and reliable products to each client, facilitating the operation with each one of them.",
    "about_l5": " ",
    "about_l6": " ",

    "cobranding_l1": "Our Co-branding business plan was forged to offer a line of hygiene and sanitary protection items that is tailored to the needs and needs of each client, providing a differentiated professional service.",
    "cobranding_l2": "In the merger, we seek to highlight the values of your company, achieving an excellent corporate image, protecting all your work areas through our products and services.",
    "cobranding_l3": "",
    "cobranding_l4": "",

    "shipping_l1": "If you buy in our online store you can receive the order at your home within 48 hours.",
    "shipping_l2": "We do private shipping to Pilar, Del Viso, Grand Bourg, Tortugitas, Ingeniero Maschwitz, Tigre for $ 300. Shipping can be free if your purchase exceeds $ 3000.",
    "shipping_l3": "To know the final cost of the shipment you must check before finalizing the order in the shopping cart.",
    "shipping_l4": "",
    "shipping_l5": "",

    "form_success": "The form was sent successfully. We will be in touch soon",
    "form_error": "Hubo un error enviando el formulario. Por Favor, vuelva a intentar más tarde",

    "ficha_t": "See Technical Sheet",
    "dficha_t": "Download Datasheet",
    "ped1": "Our team will begin to process your order and will contact you shortly.",
    "ped2": "You will receive an email with the reference data of your order, to be able to follow up.",
    "ped3": "To log in cliente panel,",
    "ped4": "click here",
    "ped5": "To return to the store",
    "ped6": "",
    "ped7": "",
    "cartipo_n": "BUY NEW",
    "cartipo_e": "MODIFICATION OF ORDER #",
    "cartipo_x": "CANCEL ORDER MODIFICATION",

    "reg_ok1": "We have sent a verification email to the box",
    "reg_ok2": "Check your email to validate it, if you have not received the email press the button",
    "reg_ok3": "RE SEND EMAIL",
    "reg_ok4": "Wait for our team to review the data provided to give you the customer REGISTRATION, soon your account will be active",
};
