export const m =
{
    "contact": "Contacto",
    "hygiene": "Higiene",
    "clothes": "Ropa",
    "industry": "Industria",
    "home": "Hogar",
    "Home": "Hogar",
    "about": "Nosotros",
    "reseller": "Grandes Clientes",
    "total_amount" :"Total compra",
    "quantity_items" :"Cantidad Art",
    "average" :"Promedio",
    "search" :"Buscar",
    

    "subscribe" :"Suscribite",
    "follow": "Seguinos",
    "shiping" :"ENVIO",
    "faq" :"PREGUNTAS FRECUENTAS",
    "how_to_buy" :"COMO COMPRAR",
    "cobranding" :"COBRANDING",

    "send": "Enviar",
    "cancel": "Cancelar",
    "modify": "Modificar",
    "save": "Guardar",
    "update": "Actualizar",
    "acept": "Aceptar",
    "new": "Nuevo",
    "high": "Alta",
    "anular_p": "Anular Pedido",
    "go_back": "Regresar",
    "code" : "Codigo de Verificación",
    "validate_mail" : "Validar Email",
    "validate_mail_ok" : "Email Validado Correctamente",
    "validate_mail_error" : "Codigo de Confirmación Invalido",

    "suscription_success": "Registrado con éxito. Pronto recibirá todas nuestras novedades",
    "suscription_error": "Hubo un error registrando el correo. Por favor, vuelva a intentarlo más tarde",
    "reseller_email_error":"Correo ya registrado. Si no recuerda su clave puede solicitar un blanqueo",
    "reseller_id_error":"CUIT o DNI ya registrado. Si no recuerda su clave puede solicitar un blanqueo",
    "reseller_success":"Se envió el formulario con éxito. Pronto nos pondremos en contacto",
    "reseller_error":"Hubo un error enviando el formulario. Por favor, vuelva a intentar más tarde",

    "max_lenght_error": "Ha excedido la cantidad máxima de caracteres.",
    "email_error": "Por favor, ingrese un formato de correo válido.",
    "min_lenght_error": "Ingreso minimo de caracteres :",
    "required_error": "Por favor, complete todos los campos.",
    "choose_state":"Seleccione una provincia",
    "choose_city":"Seleccione una localidad",
    "message_numeric":"Ingrese solo números, sin espacios, guiones ni puntos",
    "ok_message":"Correcto",
    "limit_numeric":"Ingrese 4 dígitos",

    "my_perfil": "Mi Perfil",
    "my_datos": "Mis Datos",
    "datos_g": "Datos Generales",
    "t_client": "Tipo de Clientes",
    "a_client": "Administración de Clientes",
    "client": "Clientes",
    "confirm_delet_cliente1": "Seguro que desea Eliminar el Cliente",
    "confirm_delet_cliente2": "Esta acción no puede deshacerse. Recuede que no puede Eliminar Clientes que tengan Pedidos y/o Facturas realizadas",
    "send_email_clave": "Enviar correo al Usuario con nueva Clave ? ",
    "usuario_edit": "Se Actualizó los Datos Correctamente",
    "usuario_edit_error": "Hubo un error General al Actualizar los Datos",

    "most_wanted": "Los más buscados",

    "about_as": "Sobre Nosotros",
   
    "categories": "Categorias",
    "howbuy": "Como comprar",

    "presentations": "Presentaciones:",
    "buy": "COMPRAR",
    "buy_now": "Ingrese Para Comprar",
    "select_packaging": "Seleccione Envases",
    "related_items": "Artículos Relacionados",
    "modal_title": "Producto agregado al carrito",
    "modal_btn_categories": "Volver a la categoría",
    "modal_btn_categories_home": "Ir a categoría casa",
    "modal_btn_categories_hygiene": "Ir a categoría higiene",
    "modal_btn_categories_clothes": "Ir a categoría ropa",
    "btn_categories": "Ir a la Categorías ",

    "modal_btn_close": "Mantenerme en esta página",
    "modal_btn_cart": "Ver el carrito",
    "now": "AHORA",

    "from": "desde",


    "full_name":"Nombre Completo o Razón Social",
    "cuit":"CUIT o DNI",
    "state":"Provincia",
    "street":"Dirección",
    "between_streets": "Entre Calles",
    "city":"Localidades",
    "zip":"Codigo Postal",
    "number":"Numero",
    "floor":"Piso/Depto",
    "address_required": "Dirección es Requerida",
    "d_fact": "Datos Financieros",
    "saldo_f": "Total Saldo Pendiente",
    "estado": "Estado",
    "obsv": "Observación",


   "item":"Articulo",
   "amount":"Subtotal",
   "unitary": "Unitario",
   "go_checkout":"Confirmar Compra",
   "keep_buying":"Seguir comprando",
   "empty_cart":"Vaciar carro",
   "checkout":"Finalizar Pedidos Nuevo",
   "checkout2": "Finalizar Modificación de Pedido # ",
   "date_delivery": "Fecha Aproximada de Entrega",
   "obsv": "Observación",


   "id":"Información personal",
    "shipping_address":"Dirección de Envío",
    "payment":"Pago",
    "summary":"Resumen de Compra",
    "close":"Cerrar",
    "first_name": "Nombre",
    "last_name": "Apellido",
    "celphone": "Celular",
    "goto_shipp": "ir a envío",
    "bill_info" : "En el caso de necesitar una factura A o B a nombre de otra parsona podrá solicitarlo en el panel de usuario una vez concretado el pedido.",
    "goto_payment" : "ir al pago",
    "autorize_shipping" : "Completar si recibe o retira otra persona",
    "make_order" : "Realizar Pedido",
    "subtotal": "Subtotal",
    "shipping": "Envío",
    "total": "Total",
    "discount": "Descuento",
    "free_shipping": "Envío Gratuito",


    "leave_message": "Dejanos tu mensaje",
    "ForWhom": "¿A quién está dirigida tu consulta?",
    "name": "Nombre",
    "email": "Correo",
    "phone": "Telefono",
    "message": "Mensaje",
    "customer_support": "Atención al cliente",
    "reseller_support": "Canal Mayorista",

    "order_complete":"PEDIDO COMPLETADO",
    "thanks_order":"MUCHAS GRACIAS POR SU COMPRA",
    
    "password": "Contraseña",
    "repeartpassword": "Repetir Contraseña",
    "password_min": "Contraseña Minima de 8 Caracteres",
    "password_mismatch": "La Contraseña no Coinciden",
    "password_ok": "Contraseña Ok",
    "password_success": "Se Modifico la Contraseña del Usuario Correctamente",
    "password_error": "Hubo un Error Modificando la contraseña, favor comuniquese con el administrador",
    "password_new": "Escriba una Nueva Contraseña",
    "password_change": "Cambiar Clave",


    "welcome_l1": " Bienvenido al área de Clientes de Swell.com.ar",
    "welcome_l2": " Si usted ya posee una cuenta,",
    "welcome_l22": " haga click aqui. ",
    "welcome_l3": " Si quiere comenzar a comprar y/o vender nuestros productos, complete el siguiente formulario y a continuación un representante de nuestro equipo se pondrá en contacto con usted a la brevedad. ",
    "welcome_l4": " Gracias! El Equipo de Swell ",

    "about_l1": " es una empresa que cuenta con una trayectoria de 15 años en la fabricación de productos de higiene y limpieza, con constantes inversiones en tecnología y desarrollo de nuevos productos. Contamos con altos standards de calidad a precios muy competitivos.",
    "about_l2": " Somos una compañia comprometida con el medio ambiente, el desarrollo personal y profesional de quienes la componen capacitandonos constantemente.",
    "about_l3": " Agregamos valor en toda la cadena adaptándonos a las necesidades de nuestros clientes, brindandoles un excelente servicio. Inicialmente enfatizamos nuestras producciones y comercialización en diversas industrias de todo el pais, logrando la expansión de nuestro negocio introduciendonos en los canales de distribuidores, mayoristas y finalmente con presencia en el consumidor final como asi también en el mercado de exportación.",
    "about_l4": " Nuestra Misión es hacer llegar productos de alta calidad y confiabilidad a cada cliente, facilitando la operación con cada uno de ellos.",
    "about_l5": " ",
    "about_l6": " ",

    "cobranding_l1": "Nuestro plan de negocios Co-branding se forjó para ofrecer una línea de articulos de higiene y protección sanitaria que se adapta a la medida y necesidad de cada cliente, brindando un servicio profesional diferenciado.",
    "cobranding_l2": "En la fusión buscamo destacar los valores de tu empresa, logrando una excelente imagen corporativa, protegiendo todas tus áreas de trabajo a través de nuestros productos y servicios.",
    "cobranding_l3": "",
    "cobranding_l4": "",

    "shipping_l1": "Si compras en nuestra tienda online podes recibir el pedido en tu domicilio dentro de las 48 horas.",
    "shipping_l2": "Hacemos envíos privado a Pilar, Del Viso, Grand Bourg, Tortugitas, Ingeniero Maschwitz, Tigre por $300. Los envíos pueden ser gratis si tu compra supera los $3000.",
    "shipping_l3": "Para conocer el costo final del envio debe fijarte antes de finalizar el pedido en el carrito de compras.",
    "shipping_l4": "",
    "shipping_l5": "",

    "form_success": "Se envió el formulario con éxito. Pronto nos pondremos en contacto",
    "form_error": "Hubo un error enviando el formulario. Por Favor, vuelva a intentar más tarde",

    "ficha_t": "Ver Ficha Técnica",
    "dficha_t": "Descargar Ficha Técnica",
    "ped1": "Nuestro equipo comenzará a procesar tu pedido y se pondrá en contacto contigo a la brevedad.",
    "ped2": "Te llegará un correo con los datos de referencia de tu pedido, para poder hacer seguimiento.",
    "ped3": "Para iniciar sessión en el panel de cliente,",
    "ped4": "haga click aqui",
    "ped5": "Para volver a la tienda",
    "ped6": "",
    "ped7": "",
    "cartipo_n": "COMPRA NUEVA",
    "cartipo_e": "MODIFICACION DE PEDIDO #",
    "cartipo_x": "CANCELAR MODIFICACION DE PEDIDO",

    "reg_ok1": "Hemos enviado un correo de verificación a la casilla de ",
    "reg_ok2": "Revise su correo para validarlo, si no a recibido el correo presione el boton de ",
    "reg_ok3": "RE ENVIAR EMAIL",
    "reg_ok4": "Espere a que nuestro equipo revise los datos suministrados para darle el ALTA de cliente, pronto su cuenta estará activa",
};
